export interface customer{
    userId: string,
    email: string,
    phoneNumber: string,
    country?: string,
    pin:string,
    firstName: string,
    lastName: string,
    username: string,
    isOnboarded: string,
    isActivated: boolean,
    isApproved: boolean,
    isBloacked: boolean,
    userIsSoftDeleted: boolean,
    verifiedEmail: boolean,
    selfieId: string,
    selfieCloudinaryId: string,
    documentId: string,
    documentCloudinaryId: string,
    govtDocId?:string,
    govtDocCloudinaryId?:string,
    utilityDoc:string,
    utilityDocCloudinaryId?:string,
    bvn:string,
    nin:string,
    lastLoginAt:string,
    d_o_b:string,
    photoId?:string,
    role?:string,
    cloudinaryId?:string,
    gender?:string,
    title?:string,
    bankName?:string,
    bankAccountNumber?:string,
    accountName?:string,
    accountSurName?:string,
    accountFirstName?:string,
    accountMiddleName?:string,
    referralCode?:string,
    preferredBg?:string,
    createdAt: string,
    updatedAt: string
}